# Generated by Django 3.1.6 on 2022-06-25 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertising', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(max_length=3000)),
                ('source', models.URLField()),
                ('is_cover_story', models.BooleanField(default=False)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('ad', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='advertising.advertisement')),
                ('divesite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxonomy.divesite')),
                ('topics', models.ManyToManyField(to='taxonomy.Topic')),
            ],
        ),
    ]
