# Generated by Django 3.1.6 on 2022-06-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
        ('news', '0002_auto_20220625_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='advertising.advertisement'),
        ),
    ]
